# Generated by Django 3.1.6 on 2021-04-10 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(default=uuid.uuid4, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('option', models.IntegerField(choices=[(0, 'User-Added'), (1, 'Hard-Coded'), (2, 'General')])),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
