# Generated by Django 3.1.6 on 2021-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210410_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemCode',
            new_name='item_code',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='maxQuantity',
            new_name='max_quantity',
        ),
        migrations.AlterField(
            model_name='category',
            name='option',
            field=models.IntegerField(choices=[(0, 'User-added'), (1, 'Hardcoded'), (2, 'General')]),
        ),
    ]
